### 1. Two Sum

In [2]:
class xyz1:
    def myfunc1(self):
        # Take input from the user
        nums_input = input("Enter your numbers separated by commas: ")
        numbers_list = nums_input.split(',')
        numbers_list = [int(num) for num in numbers_list]
        target = int(input("Enter your target: "))
        
        # Use a dictionary to store the complement of each number
        num_index_map = {}
        
        # Iterate over the numbers_list to find the indices
        for i, num in enumerate(numbers_list):
            complement = target - num
            # Check if the complement exists in the dictionary
            if complement in num_index_map:
                # If found, return the indices
                return [num_index_map[complement], i]
            # Otherwise, store the current number and its index in the dictionary
            num_index_map[num] = i
        
        # If no solution is found, return None
        return None

func1 = xyz1()

result = func1.myfunc1()

if result:
    print(f"The indices of the two numbers that add up to the target are: {result}")
else:
    print("No solution found.")


Enter your numbers separated by commas: 1,5,6,7
Enter your target: 6
The indices of the two numbers that add up to the target are: [0, 1]


In [16]:
def delta(x): 
    
    if x == 0: 
        y = 1 
    else: 
        y = 0 
    return y

In [17]:
a = 1 


def do(x): 
    return x + a 


print(do(1))


2


In [53]:
import numpy as np
a = np.array([10,2,8])
b = np.array([1,2,2])
c = a + b
print(c)
type(a)
d = 2 * c
print(d)
e =np.dot(c,d)
print(e)

a.shape

f = np.array([[1,2,3],[4,5,6]])
g = np.array([[1,2,3]])
print(type(f))
print(type(g))
h = g + f
print(h)

[11  4 10]
[22  8 20]
474
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[[2 4 6]
 [5 7 9]]


In [59]:
X=np.array([[1,0],[0,1]]) 

Y=np.array([[2,1],[1,2]]) 

Z=np.dot(X,Y) 
Z

array([[2, 1],
       [1, 2]])